name: matilda
services:
  
  coduo:
    build:
      context: .
      dockerfile: coduo-Dockerfile
    container_name: coduo
    ports:
      - "28960:28960"
      - "28960:28960/UDP"
      - "20500:20500/UDP"
      - "20510:20510/UDP"
      - "20600:20600/UDP"
      - "20610:20610/UDP"
    restart: unless-stopped
    volumes:
      - "./data_seeded/coduo:/coduo"

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./data_env/mysql.env
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./data_seeded/mysql/ultrastats.sql.gz:/docker-entrypoint-initdb.d/ultrastats.sql.gz"

  caddy:
    image: caddy:2
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/UDP"
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - "./data_configs/caddy:/etc/caddy"
      - "./data_seeded/coduo/:/var/www/coduomaps/"
      - "./data_seeded/bia_old/:/var/www/bia_old/"
      - "./data_seeded/caddyroots/matilda:/var/www/matilda/"

  ultrastats:
    depends_on: 
      - mysql
    image: nibrev/php-5.3-apache
    restart: unless-stopped
    volumes:
      - "./data_seeded/coduo/BrothersInArms_mod/games_mp.log:/games_mp.log"
      - "./data_seeded/ultrastats/src:/var/www/html"

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
