name: matilda
services:
  
  coduo:
    build:
      context: .
      dockerfile: coduo-Dockerfile
    container_name: coduo
    ports:
      - target: 28960
        published: 28960
        protocol: tcp
        mode: host
      - target: 20500
        published: 20500
        protocol: udp
        mode: host
      - target: 20510
        published: 20510
        protocol: udp
        mode: host
      - target: 20600
        published: 20600
        protocol: udp
        mode: host
      - target: 20610
        published: 20610
        protocol: udp
        mode: host
      - target: 28960
        published: 28960
        protocol: udp
        mode: host
    restart: unless-stopped
    volumes:
      - "./data_seeded/coduo:/coduo"

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./data_env/mysql.env
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./data_seeded/mysql/ultrastats.sql.gz:/docker-entrypoint-initdb.d/ultrastats.sql.gz"

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - "./data_configs/caddy:/etc/caddy"
      - "./data_seeded/coduo/:/var/www/coduomaps/"
      - "./data_seeded/bia_old/:/var/www/bia_old/"
      - "./data_seeded/caddyroots/matilda:/var/www/matilda/"

  ultrastats:
    depends_on: 
      - mysql
    image: php:5.3-apache
    restart: unless-stopped
    volumes:
      - "./data_seeded/coduo/BrothersInArms_mod/games_mp.log:/games_mp.log"
      - "./data_seeded/ultrastats/src:/var/www/html"

volumes:
  mysql_data:
